apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: python-4june 
  janus-idp.io/tekton: python-4june
  backstage.io/kubernetes-id: python-4june
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: python-4june
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  